### ISSUE TITLE
DEMO

### ISSUE THREAD

**Issue by mgood7123** [flipkart-incubator/proteus#140]
Failed to connect to /10.0.2.2:8080

upon tapping the refresh button

**Comment by adityasharat** [comment]
Are you running the demo application on an emulator or a physical device?

**Comment by mgood7123** [comment]
Omfg how do I block you, your spamming me

**Comment by mgood7123** [comment]
Plus you are NOT the developer of Proteus

**Comment by adityasharat** [comment]
I'm! 👀 
<img width="797" alt="Screen Shot 2019-03-10 at 16 47 26" src="https://user-images.githubusercontent.com/1552857/54088292-7756c580-4354-11e9-95f0-dbe6a5afaabb.png">

**Comment by mgood7123** [comment]
I don't know what that means

**Comment by mgood7123** [comment]
Also why do you post issues if, assume collaborator means you help manage
the source code, you can just submit a patch/pull request for the source

**Comment by adityasharat** [comment]
I didn't post any issues, I was simply replying on the issues that you posted.

Anyone can submit an issue (even the contributors of the project). The issue page is a place where developers can discuss about the issue/feature request/question and their solutions.

Questions should be mostly posted on stack overflow though.

**Comment by mgood7123** [comment]
ok

**Comment by mgood7123** [comment]
> 
> 
> Are you running the demo application on an emulator or a physical device?

physical device

**Comment by adityasharat** [comment]
#### A guess to why it is failing

Since you are using a physical device and not an emulator the application is not able to communicate to the node server hosting the layout, since it expects to run on an emulator by default.

Please change the ip address to your machine ip address [here](https://github.com/flipkart-incubator/proteus/blob/master/demo/src/main/java/com/flipkart/android/proteus/demo/DemoApplication.java#L31). 

> `10.0.2.2` in emulators is the host machine's localhost.

**Comment by mgood7123** [comment]
oh

**Comment by adityasharat** [comment]
Assuming this is no longer an issue. Closing.
