### ISSUE TITLE
not working with existing ids?

### ISSUE THREAD

**Issue by Manju96** [flipkart-incubator/proteus#68]
i have tried to use proteus in my app.But its not working.  i want change color  and other attributes in the textview.But it is not working. will proteous support existing ids which is inflated by LayoutInflator

**Comment by adityasharat** [comment]
Short answer: `no` you cannot.
View `id` (an int) is generated at compile time when you write layouts in `XML`, and in proteus, View `id` are String. So proteus simulates the id generation logic at runtime, hence will not be the same as `R.id.something`. In order to find a view by id please follow this example.

Layout: 

```json
{
  "type": "TextView",
  "id": "myId"
}
```

Java code:

```java
int id = layoutBuilder.getUniqueViewId("myId");
View view = proteusView.findViewById(id);
```
